param(
    [Parameter(Mandatory = $true)][string]$Atdf,
    [Parameter(Mandatory = $true)][string]$Output
)

$ErrorActionPreference = 'Stop'
[xml]$device = Get-Content -LiteralPath $Atdf
$deviceName = $device.'avr-tools-device-file'.devices.device.name
$wantedPackages = @('TFBGA120', 'TQFP128')
$rows = [System.Collections.Generic.List[object]]::new()
$seenPinouts = @{}

foreach ($variant in $device.'avr-tools-device-file'.variants.variant) {
    if ($variant.package -notin $wantedPackages) { continue }
    $pinoutKey = "$($variant.package)/$($variant.pinout)"
    if ($seenPinouts.ContainsKey($pinoutKey)) { continue }
    $seenPinouts[$pinoutKey] = $true
    $pinout = $device.'avr-tools-device-file'.pinouts.pinout |
        Where-Object { $_.name -eq $variant.pinout } |
        Select-Object -First 1
    $positions = @{}
    foreach ($pin in $pinout.pin) { $positions[$pin.pad] = $pin.position }

    foreach ($module in $device.'avr-tools-device-file'.devices.device.peripherals.module) {
        foreach ($instance in $module.instance) {
            foreach ($signal in $instance.signals.signal) {
                if (-not $positions.ContainsKey($signal.pad)) { continue }
                $rows.Add([pscustomobject]@{
                    package = $variant.package
                    pinout = $variant.pinout
                    position = $positions[$signal.pad]
                    pad = $signal.pad
                    peripheral = $instance.name
                    signal = $signal.group
                    index = if ($null -eq $signal.index) { '' } else { $signal.index }
                    function = $signal.function
                    ioset = if ($null -eq $signal.ioset) { '' } else { $signal.ioset }
                })
            }
        }
    }
}

$metadata = @(
    '# Generated by tools/extract-microchip-atdf-routes.ps1',
    "# device=$deviceName",
    '# source=Microchip.SAMD51_DFP.3.9.276/samd51a/atdf/ATSAMD51P19A.atdf',
    '# source_url=https://packs.download.microchip.com/Microchip.SAMD51_DFP.3.9.276.atpack',
    '# license=Apache-2.0 (Microchip device pack)'
)
$csv = $rows |
    Sort-Object package, pad, peripheral, signal, index, function |
    ConvertTo-Csv -NoTypeInformation
[IO.File]::WriteAllLines($Output, $metadata + $csv, [Text.UTF8Encoding]::new($false))
